name: Deploy Helm Chart

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.0

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install niche-explorer helm/niche_explorer \
            --namespace team-dev-ops \
            -f helm/niche_explorer/values.yaml
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}
