name: Deploy Helm Chart

on:
  workflow_run:
    workflows: [Build Docker Images]
    types:
      - completed

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.0

      - name: Set up Kubeconfig
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install niche-explorer helm/niche_explorer \
            --namespace team-dev-ops
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}
